# Modern golangci-lint configuration
run:
  timeout: 5m
  tests: true

linters-settings:
  staticcheck:
    checks: ["all", "-SA1019", "-SA1029"]
  revive:
    rules:
      - name: receiver-naming
        severity: warning
        disabled: false

linters:
  disable-all: true
  enable:
    - bidichk
    - copyloopvar
    - durationcheck
    - gocheckcompilerdirectives
    - govet
    - ineffassign
    - mirror
    - misspell
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unused
    - usetesting
    - whitespace

issues:
  exclude-rules:
    - path: crypto/bn256/cloudflare/optate.go
      linters:
        - staticcheck
    - path: cmd/utils/flags.go
      text: "SA1019: cfg.TxLookupLimit is deprecated: use 'TransactionHistory' instead."
    - path: cmd/utils/flags.go
      text: "SA1019: ethconfig.Defaults.TxLookupLimit is deprecated: use 'TransactionHistory' instead."
    - path: internal/build/pgp.go
      text: 'SA1019: "golang.org/x/crypto/openpgp" is deprecated: this package is unmaintained except for security fixes.'
    - path: core/vm/contracts.go
      text: 'SA1019: "golang.org/x/crypto/ripemd160" is deprecated: RIPEMD-160 is a legacy hash and should not be used for new applications.'
    - path: (.+)\.go$
      text: 'SA1019: event.TypeMux is deprecated: use Feed'
    - path: (.+)\.go$
      text: 'SA1019: strings.Title is deprecated'
    - path: (.+)\.go$
      text: 'SA1019: strings.Title has been deprecated since Go 1.18'
    - path: (.+)\.go$
      text: 'SA1029: should not use built-in type string as key for value'
  exclude-dirs:
    - third_party
    - builtin
    - examples
  exclude-files:
    - core/genesis_alloc.go
